In [1]:
import pandas as pd
from google.colab import files

uploaded =files.upload()

Saving entradas_breast.csv to entradas_breast.csv


In [3]:
import io
  
previsores = pd.read_csv(io.BytesIO(uploaded['entradas_breast.csv']))

In [4]:
uploaded =files.upload()

Saving saidas_breast.csv to saidas_breast.csv


In [5]:
classe = pd.read_csv(io.BytesIO(uploaded['saidas_breast.csv']))

As validações utilizando as bases de teste foram feitas nos projetos anteriores portanto agora os melhores valores são colocados nos respectivos valores

In [7]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout

classificador=Sequential()

#Primeira camada oculta
classificador.add(Dense(units =8, activation= 'relu',
                        kernel_initializer='normal', input_dim=30)) 

#camada de dropout, passando o parametro da porcentagem que eu quero zerar
classificador.add(Dropout(0.2))

#Segunda camada oculta  
classificador.add(Dense(units =8, activation= 'relu', 
                        kernel_initializer='normal')) 
classificador.add(Dropout(0.2))

#camada de saida
classificador.add(Dense(units =1, activation= 'sigmoid')) 

classificador.compile(optimizer='adam', loss='binary_crossentropy', 
                      metrics=['binary_accuracy'])

classificador.fit(previsores,classe,batch_size=10, epochs=100)

Epoch 1/100
57/57 [==============================] - 1s 1ms/step - loss: 4.2470 - binary_accuracy: 0.5378
Epoch 2/100
57/57 [==============================] - 0s 1ms/step - loss: 0.9194 - binary_accuracy: 0.6274
Epoch 3/100
57/57 [==============================] - 0s 1ms/step - loss: 0.9586 - binary_accuracy: 0.6292
Epoch 4/100
57/57 [==============================] - 0s 1ms/step - loss: 0.6416 - binary_accuracy: 0.6221
Epoch 5/100
57/57 [==============================] - 0s 1ms/step - loss: 0.5692 - binary_accuracy: 0.6960
Epoch 6/100
57/57 [==============================] - 0s 1ms/step - loss: 0.5327 - binary_accuracy: 0.7241
Epoch 7/100
57/57 [==============================] - 0s 1ms/step - loss: 0.5192 - binary_accuracy: 0.7399
Epoch 8/100
57/57 [==============================] - 0s 1ms/step - loss: 0.5308 - binary_accuracy: 0.7645
Epoch 9/100
57/57 [==============================] - 0s 1ms/step - loss: 0.4945 - binary_accuracy: 0.7329
Epoch 10/100
57/57 [==========================

Na variavel *classificador* ja tem-se a rede neural final, isto é, a estrutura da rede neural junto com o conjunto dos pesos.


In [13]:
import numpy as np

#dados aleatorios dados aos 30 atributos (radius_mean,texture_mean,...)
novo= np.array([[15.80, 8.34, 118, 900, 0.10, 0.26, 0.08, 0.134, 0.178,
                  0.20, 0.05, 1098, 0.87, 4500, 145.2, 0.005, 0.04, 0.05, 0.015,
                  0.03, 0.007, 23.15, 16.64, 178.5, 2018, 0.14, 0.185,
                  0.84, 158, 0.363]])
novo

array([[1.580e+01, 8.340e+00, 1.180e+02, 9.000e+02, 1.000e-01, 2.600e-01,
        8.000e-02, 1.340e-01, 1.780e-01, 2.000e-01, 5.000e-02, 1.098e+03,
        8.700e-01, 4.500e+03, 1.452e+02, 5.000e-03, 4.000e-02, 5.000e-02,
        1.500e-02, 3.000e-02, 7.000e-03, 2.315e+01, 1.664e+01, 1.785e+02,
        2.018e+03, 1.400e-01, 1.850e-01, 8.400e-01, 1.580e+02, 3.630e-01]])

Esses dados dão o resultado 1 (True), o que indica que é um tumor maligno

In [14]:
previsao = classificador.predict(novo)
previsao

array([[1.]], dtype=float32)

In [16]:
previsao = (previsao > 0.9)
previsao


array([[ True]])