In [1]:
import pandas as pd

previsores = pd.read_csv('entradas_breast.csv')
classe = pd.read_csv('saidas_breast.csv')

In [2]:
previsores

radius_mean   texture_mean  ...   symmetry_worst   fractal_dimension_worst
0           17.99          10.38  ...           0.4601                   0.11890
1           20.57          17.77  ...         275.0000                   0.08902
2           19.69          21.25  ...           0.3613                   0.08758
3           11.42          20.38  ...           0.6638                 173.00000
4           20.29          14.34  ...           0.2364                   0.07678
..            ...            ...  ...              ...                       ...
564         21.56          22.39  ...         206.0000                   0.07115
565         20.13          28.25  ...           0.2572                   0.06637
566         16.60          28.08  ...           0.2218                   0.07820
567         20.60          29.33  ...           0.4087                 124.00000
568          7.76          24.54  ...           0.2871                   0.07039

[569 rows x 30 columns]

In [3]:
classe

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [58]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

def criarRede():
  classificador=Sequential()
#Primeira camada oculta
#Definição da primeira camada de entrada (input_dim)
  classificador.add(Dense(units =16, activation= 'relu', kernel_initializer='random_uniform', input_dim=30)) 
#camada de dropout, passando o parametro da porentagem que eu quero zerar
  classificador.add(Dropout(0.2))
#Segunda camada oculta  
  classificador.add(Dense(units =16, activation= 'relu', kernel_initializer='random_uniform')) 
  classificador.add(Dropout(0.2))
#Terceira camada oculta  
  classificador.add(Dense(units =8, activation= 'relu', kernel_initializer='random_uniform')) 
  classificador.add(Dropout(0.2))
#camada de saida
  classificador.add(Dense(units =1, activation= 'sigmoid'))   
  otimizador= keras.optimizers.Adam(learning_rate=0.001, decay=0.0001, clipvalue=0.5)
#classificador.compile(optimizer='adam', loss='binary_crossentropy', metrics=['binary_accuracy'])
  classificador.compile(optimizer=otimizador, loss='binary_crossentropy', metrics=['binary_accuracy'])
  return classificador

In [59]:
classificador = KerasClassifier(build_fn =criarRede, epochs=100,batch_size=10)

In [60]:
resultados= cross_val_score(estimator=classificador, X=previsores, y=classe, cv=10, scoring='accuracy' )

Epoch 1/100
52/52 [==============================] - 1s 3ms/step - loss: 0.6742 - binary_accuracy: 0.6367
Epoch 2/100
52/52 [==============================] - 0s 3ms/step - loss: 0.5815 - binary_accuracy: 0.6484
Epoch 3/100
52/52 [==============================] - 0s 3ms/step - loss: 0.5653 - binary_accuracy: 0.6758
Epoch 4/100
52/52 [==============================] - 0s 3ms/step - loss: 0.5413 - binary_accuracy: 0.6777
Epoch 5/100
52/52 [==============================] - 0s 3ms/step - loss: 0.5235 - binary_accuracy: 0.7109
Epoch 6/100
52/52 [==============================] - 0s 3ms/step - loss: 0.5144 - binary_accuracy: 0.7324
Epoch 7/100
52/52 [==============================] - 0s 2ms/step - loss: 0.4850 - binary_accuracy: 0.7441
Epoch 8/100
52/52 [==============================] - 0s 2ms/step - loss: 0.5038 - binary_accuracy: 0.7617
Epoch 9/100
52/52 [==============================] - 0s 2ms/step - loss: 0.4672 - binary_accuracy: 0.7402
Epoch 10/100
52/52 [==========================

In [61]:
resultados

array([0.85964912, 0.87719298, 0.94736842, 0.85964912, 0.9122807 ,
       0.96491228, 0.89473684, 0.94736842, 0.85964912, 0.92857143])

In [62]:
media = resultados.mean()
media
#media sem o dropout (0.7924185463659148)
#media units=16 (0.8628759398496241)
#media units=32 (0.8611215538847118)
#media units=16 (1ª camada) units=8 (2ªcamada) (0.8735902255639099)

0.9051378446115288

In [63]:
#Quantos valores estão variando em relação a média (0.79)
# Quanto maior o valor maior a probabilidade de overfitting
desvio= resultados.std()
desvio
#desvio sem o dropout (0.08553035509662345)
#desvio com units=16 (0.08115982894881578)
#desvio com units=32 (0.06209555321111705)
#desvio com units=16 (1ª camada) units=8 (2ªcamada) (0.07215467272594663)

0.038518498486587845



---

#Classificando um unico registro



In [66]:
classificador=Sequential()
#Primeira camada oculta
#Definição da primeira camada de entrada (input_dim)
classificador.add(Dense(units =16, activation= 'relu', kernel_initializer='random_uniform', input_dim=30)) 
#camada de dropout, passando o parametro da porentagem que eu quero zerar
classificador.add(Dropout(0.2))
#Segunda camada oculta  
classificador.add(Dense(units =16, activation= 'relu', kernel_initializer='random_uniform')) 
classificador.add(Dropout(0.2))
#Terceira camada oculta  
classificador.add(Dense(units =8, activation= 'relu', kernel_initializer='random_uniform')) 
classificador.add(Dropout(0.2))
#camada de saida
classificador.add(Dense(units =1, activation= 'sigmoid'))   
otimizador= keras.optimizers.Adam(learning_rate=0.001, decay=0.0001, clipvalue=0.5)
#classificador.compile(optimizer='adam', loss='binary_crossentropy', metrics=['binary_accuracy'])
classificador.compile(optimizer=otimizador, loss='binary_crossentropy', metrics=['binary_accuracy'])

In [67]:
classificador.fit(previsores,classe,batch_size=10, epochs=100)

Epoch 1/100
57/57 [==============================] - 1s 3ms/step - loss: 0.6621 - binary_accuracy: 0.5624
Epoch 2/100
57/57 [==============================] - 0s 3ms/step - loss: 0.5734 - binary_accuracy: 0.6555
Epoch 3/100
57/57 [==============================] - 0s 2ms/step - loss: 0.5313 - binary_accuracy: 0.6591
Epoch 4/100
57/57 [==============================] - 0s 3ms/step - loss: 0.5206 - binary_accuracy: 0.6995
Epoch 5/100
57/57 [==============================] - 0s 3ms/step - loss: 0.5104 - binary_accuracy: 0.7645
Epoch 6/100
57/57 [==============================] - 0s 3ms/step - loss: 0.4554 - binary_accuracy: 0.7996
Epoch 7/100
57/57 [==============================] - 0s 3ms/step - loss: 0.4666 - binary_accuracy: 0.8120
Epoch 8/100
57/57 [==============================] - 0s 3ms/step - loss: 0.4333 - binary_accuracy: 0.8260
Epoch 9/100
57/57 [==============================] - 0s 3ms/step - loss: 0.3999 - binary_accuracy: 0.8278
Epoch 10/100
57/57 [==========================

In [68]:
import numpy as np

#dados aleatorios dados aos 30 atributos (radius_mean,texture_mean,...)
novo= np.array([[15.80, 8.34, 118, 900, 0.10, 0.26, 0.08, 0.134, 0.178,
                  0.20, 0.05, 1098, 0.87, 4500, 145.2, 0.005, 0.04, 0.05, 0.015,
                  0.03, 0.007, 23.15, 16.64, 178.5, 2018, 0.14, 0.185,
                  0.84, 158, 0.363]])
novo

array([[1.580e+01, 8.340e+00, 1.180e+02, 9.000e+02, 1.000e-01, 2.600e-01,
        8.000e-02, 1.340e-01, 1.780e-01, 2.000e-01, 5.000e-02, 1.098e+03,
        8.700e-01, 4.500e+03, 1.452e+02, 5.000e-03, 4.000e-02, 5.000e-02,
        1.500e-02, 3.000e-02, 7.000e-03, 2.315e+01, 1.664e+01, 1.785e+02,
        2.018e+03, 1.400e-01, 1.850e-01, 8.400e-01, 1.580e+02, 3.630e-01]])

In [69]:
previsao = classificador.predict(novo)
previsao

array([[0.99999195]], dtype=float32)

In [70]:
previsao = (previsao > 0.9)
previsao

array([[ True]])