In [3]:
import pandas as pd

base = pd.read_csv('iris.csv')
base

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
previsores=base.iloc[:, 0:4].values
previsores

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
#coluna 4
classe= base.iloc[:, 4].values
classe

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

Convertendo os valores categóricos para valores numéricos da *Classe*


In [13]:
from sklearn.preprocessing import LabelEncoder

labelencoder=LabelEncoder()
classe=labelencoder.fit_transform(classe)
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

iris setosa :   1 0 0

iris virginica: 0 1 0

iris versicolor: 0 0 1

In [14]:
from keras.utils import np_utils

classe_dummy=np_utils.to_categorical(classe)
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

Dividindo a base de dados em treinamento e teste

In [15]:
from sklearn.model_selection import train_test_split

previsores_treinamento,previsores_teste,classe_treinamento,classe_teste=train_test_split(previsores,classe_dummy,test_size=0.25)

Construção da estrutura da rede neural

units=(4 entradas + 3 saidas)/2 =3.5=4

In [16]:
from keras.models import Sequential
from keras.layers import Dense

classificador=Sequential()
#Primeira camada
classificador.add(Dense(units=4, activation='relu',input_dim=4))
#Segunda camada
classificador.add(Dense(units=4, activation='relu'))
#Camada de saída
#softmax: para problema de classificação com mais de duas classes
#outro exemplo de metrica: kullback_leiber_divergency
classificador.add(Dense(units=3, activation='softmax'))
classificador.compile(optimizer='adam', loss='categorical_crossentropy',
                      metrics='categorical_accuracy')

In [18]:
classificador.fit(previsores_treinamento,classe_treinamento, batch_size=10, epochs=1000)

Epoch 1/1000
12/12 [==============================] - 0s 1ms/step - loss: 0.4570 - categorical_accuracy: 0.7321
Epoch 2/1000
12/12 [==============================] - 0s 2ms/step - loss: 0.4564 - categorical_accuracy: 0.7232
Epoch 3/1000
12/12 [==============================] - 0s 2ms/step - loss: 0.4552 - categorical_accuracy: 0.7232
Epoch 4/1000
12/12 [==============================] - 0s 2ms/step - loss: 0.4533 - categorical_accuracy: 0.7321
Epoch 5/1000
12/12 [==============================] - 0s 2ms/step - loss: 0.4524 - categorical_accuracy: 0.7321
Epoch 6/1000
12/12 [==============================] - 0s 2ms/step - loss: 0.4509 - categorical_accuracy: 0.7321
Epoch 7/1000
12/12 [==============================] - 0s 2ms/step - loss: 0.4495 - categorical_accuracy: 0.7500
Epoch 8/1000
12/12 [==============================] - 0s 2ms/step - loss: 0.4473 - categorical_accuracy: 0.7500
Epoch 9/1000
12/12 [==============================] - 0s 2ms/step - loss: 0.4461 - categorical_accuracy:

Resultado da base de dados de teste


In [19]:
resultado=classificador.evaluate(previsores_teste,classe_teste)
resultado

2/2 [==============================] - 0s 7ms/step - loss: 0.0222 - categorical_accuracy: 1.0000


[0.022179465740919113, 1.0]

In [20]:
previsoes=classificador.predict(previsores_teste)
previsoes

array([[1.29984064e-05, 9.99983788e-01, 3.16765363e-06],
       [7.04387449e-13, 2.72430349e-02, 9.72756982e-01],
       [1.62054935e-11, 8.90085325e-02, 9.10991490e-01],
       [4.52961194e-06, 9.99988675e-01, 6.74841340e-06],
       [1.43737452e-10, 1.90184757e-01, 8.09815228e-01],
       [9.94448897e-07, 9.99987721e-01, 1.13116448e-05],
       [9.99973893e-01, 2.60569341e-05, 6.21069411e-28],
       [1.20900106e-03, 9.98791039e-01, 2.44694309e-08],
       [5.13541977e-07, 9.99510288e-01, 4.89184924e-04],
       [3.93055847e-14, 1.03100175e-02, 9.89689946e-01],
       [6.95106166e-04, 9.99304771e-01, 9.05207429e-08],
       [2.38739317e-09, 2.76777118e-01, 7.23222911e-01],
       [9.99985099e-01, 1.48417503e-05, 2.30315281e-29],
       [1.10890937e-07, 9.50749815e-01, 4.92500998e-02],
       [9.99974251e-01, 2.57046886e-05, 5.73504382e-28],
       [9.99983191e-01, 1.68597235e-05, 4.85742342e-29],
       [1.78451035e-06, 9.99795735e-01, 2.02441923e-04],
       [1.82904991e-14, 1.91882

In [21]:
previsoes=(previsoes>0.5)
previsoes

array([[False,  True, False],
       [False, False,  True],
       [False, False,  True],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [Fa

In [23]:
import numpy as np
# retorna:
#(0,1,0)-> [False,  True, False] =0, -> iris virginica
#(0,0,1)-> [False, False,  True] =1, -> iris versicolor
#(1,0,0)-> [True, False,  False] =2  -> iris setosa

classe_teste2=[np.argmax(t) for t in classe_teste]
classe_teste2

[1,
 2,
 2,
 1,
 2,
 1,
 0,
 1,
 1,
 2,
 1,
 2,
 0,
 1,
 0,
 0,
 1,
 2,
 0,
 0,
 2,
 2,
 1,
 1,
 1,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 1,
 1,
 1,
 2,
 0]

In [27]:
previsoes2=[np.argmax(t) for t in previsoes]
previsoes2

[1,
 2,
 2,
 1,
 2,
 1,
 0,
 1,
 1,
 2,
 1,
 2,
 0,
 1,
 0,
 0,
 1,
 2,
 0,
 0,
 2,
 2,
 1,
 1,
 1,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 1,
 1,
 1,
 2,
 0]

In [29]:
from sklearn.metrics import confusion_matrix

matriz=confusion_matrix(previsoes2,classe_teste2)
matriz

array([[10,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 11]])